# repos:
# -   repo: https://github.com/psf/black
#     rev: 24.4.2 # Fijar a una versión específica
#     hooks:
#     -   id: black
#         language_version: python3.11 # Especificar la versión de Python deseada
# -   repo: https://github.com/pycqa/flake8
#     rev: '7.0.0' # Revisa la última versión estable si es necesario
#     hooks:
#     -   id: flake8
